parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MediaFileService:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/uploads'

    App\Service\ApiService:
        arguments:
            $anthropicApiKey: '%env(ANTHROPIC_API_KEY)%'